; Generated by KLFC 1.5.7
; https://github.com/39aldo39/klfc

#MaxHotkeysPerInterval 200
#MaxThreadsPerHotkey 10

SendUps(ByRef modifiers) {
  for index, modifier in modifiers {
    if (modifier == "Caps")
      SetCapsLockState, off
    else if (modifier == "Num")
      SetNumLockState, off
    else if InStr(modifier, "Extend")
      %modifier% := false
    else
      Send {%modifier% Up}
  }
  modifiers := Object()
}

SendAsUnicode(string) {
  Result := ""
  Loop, Parse, string
    Result .= Format("{{}U+{:04x}{}}", Ord(A_LoopField))
  Send {Blind}%Result%
}

DeadKeys := ComObjCreate("Scripting.Dictionary")

DeadKey(baseChar, table, name := "") {
  Global ActiveDeadKey
  if (ActiveDeadKey != "") {
    NewActiveDeadKey := ComObjCreate("Scripting.Dictionary")
    for key in table {
      value := table.item(key)
      NewActiveDeadKey.item(key) := ActiveDeadKey.item(value)
    }
    result := ActiveDeadKey.item(name)
    if (IsObject(result)) {
      for key in result {
        value := result.item(key)
        NewActiveDeadKey.item(key) := value
      }
    } else if (result != "") {
      ActiveDeadKey := ""
      SendAsUnicode(result)
      Return
    }
    ActiveDeadKey := NewActiveDeadKey
    Return
  }
  ActiveDeadKey := table
  Input key, L1, {Esc}{F1}{F2}{F3}{F4}{F5}{F6}{F7}{F8}{F9}{F10}{F11}{F12}{Left}{Right}{Up}{Down}{Home}{End}{PgUp}{PgDn}{Del}{Ins}{BS}{PrintScreen}{Pause}{AppsKey}
  If InStr(ErrorLevel, "EndKey:") {
    ActiveDeadKey := ""
    value := SubStr(ErrorLevel, 8)
    Send {Blind}{%value%}
    SendAsUnicode(baseChar)
  } else if (ErrorLevel != "NewInput") {
    value := ActiveDeadKey.item(key)
    ActiveDeadKey := ""
    if (IsObject(value)) {
      DeadKey(baseChar, value)
    } else if (value != "") {
      SendAsUnicode(value)
    } else {
      SendAsUnicode(baseChar . key)
    }
  }
}

*SC02c::Send {Blind}{VK4aSC02c DownR} ; QWERTY Z: J
*SC02c up::Send {Blind}{VK4aSC02c Up}
*SC02d::Send {Blind}{VK5aSC02d DownR} ; QWERTY X: Z
*SC02d up::Send {Blind}{VK5aSC02d Up}
*SC02e::Send {Blind}{VK58SC02e DownR} ; QWERTY C: X
*SC02e up::Send {Blind}{VK58SC02e Up}
*SC02f::Send {Blind}{VK4bSC02f DownR} ; QWERTY V: K
*SC02f up::Send {Blind}{VK4bSC02f Up}
*SC030::Send {Blind}{VKbdSC030 DownR} ; QWERTY B: -
*SC030 up::Send {Blind}{VKbdSC030 Up}
*SC031::Send {Blind}{VK42SC031 DownR} ; QWERTY N: B
*SC031 up::Send {Blind}{VK42SC031 Up}
*SC032::Send {Blind}{VK4dSC032 DownR} ; QWERTY M: M
*SC032 up::Send {Blind}{VK4dSC032 Up}
*SC033::Send {Blind}{VK57SC033 DownR} ; QWERTY ,: W
*SC033 up::Send {Blind}{VK57SC033 Up}
*SC034::Send {Blind}{VK56SC034 DownR} ; QWERTY .: V
*SC034 up::Send {Blind}{VK56SC034 Up}
*SC035::Send {Blind}{VK46SC035 DownR} ; QWERTY /: F
*SC035 up::Send {Blind}{VK46SC035 Up}
*SC01e::Send {Blind}{VK41SC01e DownR} ; QWERTY A: A
*SC01e up::Send {Blind}{VK41SC01e Up}
*SC01f::Send {Blind}{VK53SC01f DownR} ; QWERTY S: S
*SC01f up::Send {Blind}{VK53SC01f Up}
*SC020::Send {Blind}{VK45SC020 DownR} ; QWERTY D: E
*SC020 up::Send {Blind}{VK45SC020 Up}
*SC021::Send {Blind}{VK55SC021 DownR} ; QWERTY F: U
*SC021 up::Send {Blind}{VK55SC021 Up}
*SC022::Send {Blind}{VKbcSC022 DownR} ; QWERTY G: ,
*SC022 up::Send {Blind}{VKbcSC022 Up}
*SC023::Send {Blind}{VKbeSC023 DownR} ; QWERTY H: .
*SC023 up::Send {Blind}{VKbeSC023 Up}
*SC024::Send {Blind}{VK4fSC024 DownR} ; QWERTY J: O
*SC024 up::Send {Blind}{VK4fSC024 Up}
*SC025::Send {Blind}{VK54SC025 DownR} ; QWERTY K: T
*SC025 up::Send {Blind}{VK54SC025 Up}
*SC026::Send {Blind}{VK48SC026 DownR} ; QWERTY L: H
*SC026 up::Send {Blind}{VK48SC026 Up}
*SC027::Send {Blind}{VK4eSC027 DownR} ; QWERTY ;: N
*SC027 up::Send {Blind}{VK4eSC027 Up}
*SC028::Send {Blind}{VK51SC028 DownR} ; QWERTY ': Q
*SC028 up::Send {Blind}{VK51SC028 Up}
*SC010::Send {Blind}{VK49SC010 DownR} ; QWERTY Q: I
*SC010 up::Send {Blind}{VK49SC010 Up}
*SC011::Send {Blind}{VK44SC011 DownR} ; QWERTY W: D
*SC011 up::Send {Blind}{VK44SC011 Up}
*SC012::Send {Blind}{VK59SC012 DownR} ; QWERTY E: Y
*SC012 up::Send {Blind}{VK59SC012 Up}
*SC013::Send {Blind}{VK50SC013 DownR} ; QWERTY R: P
*SC013 up::Send {Blind}{VK50SC013 Up}
*SC014::Send {Blind}{VKbaSC014 DownR} ; QWERTY T: ;
*SC014 up::Send {Blind}{VKbaSC014 Up}
*SC015::Send {Blind}{VKbbSC015 DownR} ; QWERTY Y: +
*SC015 up::Send {Blind}{VKbbSC015 Up}
*SC016::Send {Blind}{VK47SC016 DownR} ; QWERTY U: G
*SC016 up::Send {Blind}{VK47SC016 Up}
*SC017::Send {Blind}{VK43SC017 DownR} ; QWERTY I: C
*SC017 up::Send {Blind}{VK43SC017 Up}
*SC018::Send {Blind}{VK52SC018 DownR} ; QWERTY O: R
*SC018 up::Send {Blind}{VK52SC018 Up}
*SC019::Send {Blind}{VK4cSC019 DownR} ; QWERTY P: L
*SC019 up::Send {Blind}{VK4cSC019 Up}
*SC01a::Send {Blind}{VKdbSC01a DownR} ; QWERTY [: [
*SC01a up::Send {Blind}{VKdbSC01a Up}
*SC01b::Send {Blind}{VKddSC01b DownR} ; QWERTY ]: ]
*SC01b up::Send {Blind}{VKddSC01b Up}
*SC002::Send {Blind}{VK31SC002 DownR} ; QWERTY 1: 1
*SC002 up::Send {Blind}{VK31SC002 Up}
*SC003::Send {Blind}{VK32SC003 DownR} ; QWERTY 2: 2
*SC003 up::Send {Blind}{VK32SC003 Up}
*SC004::Send {Blind}{VK33SC004 DownR} ; QWERTY 3: 3
*SC004 up::Send {Blind}{VK33SC004 Up}
*SC005::Send {Blind}{VK34SC005 DownR} ; QWERTY 4: 4
*SC005 up::Send {Blind}{VK34SC005 Up}
*SC006::Send {Blind}{VK35SC006 DownR} ; QWERTY 5: 5
*SC006 up::Send {Blind}{VK35SC006 Up}
*SC007::Send {Blind}{VK36SC007 DownR} ; QWERTY 6: 6
*SC007 up::Send {Blind}{VK36SC007 Up}
*SC008::Send {Blind}{VK37SC008 DownR} ; QWERTY 7: 7
*SC008 up::Send {Blind}{VK37SC008 Up}
*SC009::Send {Blind}{VK38SC009 DownR} ; QWERTY 8: 8
*SC009 up::Send {Blind}{VK38SC009 Up}
*SC00a::Send {Blind}{VK39SC00a DownR} ; QWERTY 9: 9
*SC00a up::Send {Blind}{VK39SC00a Up}
*SC00b::Send {Blind}{VK30SC00b DownR} ; QWERTY 0: 0
*SC00b up::Send {Blind}{VK30SC00b Up}
*SC00c::Send {Blind}{VKbdSC00c DownR} ; QWERTY -: -
*SC00c up::Send {Blind}{VKbdSC00c Up}
*SC00d::Send {Blind}{VKbbSC00d DownR} ; QWERTY +: +
*SC00d up::Send {Blind}{VKbbSC00d Up}
*SC02b::Send {Blind}{VKdcSC02b DownR} ; QWERTY \: \
*SC02b up::Send {Blind}{VKdcSC02b Up}
*SC00e::Send {Blind}{VK8SC00e DownR} ; QWERTY Backspace: Backspace
*SC00e up::Send {Blind}{VK8SC00e Up}
*SC039::Send {Blind}{VK20SC039 DownR} ; QWERTY Space: Space
*SC039 up::Send {Blind}{VK20SC039 Up}
*SC03a::Send {Blind}{VK14SC03a DownR} ; QWERTY CapsLock: CapsLock
*SC03a up::
Send {Blind}{VK14SC03a Up}
SendUps(ModsSC03a)
Return
*SC02a::Send {Blind}{VKa0SC02a DownR} ; QWERTY Shift_L: Shift_L
*SC02a up::
Send {Blind}{VKa0SC02a Up}
SendUps(ModsSC02a)
Return
*SC036::Send {Blind}{VKa1SC036 DownR} ; QWERTY Shift_R: Shift_R
*SC036 up::
Send {Blind}{VKa1SC036 Up}
SendUps(ModsSC036)
Return

; QWERTY Z
#if not Extend
SC02c::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+006a} ; j
} else {
  Send {Blind}{U+004a} ; J
}
Return
+SC02c::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+004a} ; J
} else {
  Send {Blind}{U+006a} ; j
}
Return
>!<^SC02c::Send {Blind}{U+0023} ; #
#if Extend
*SC02c::Send {Blind}{U+002c} ; ,
+SC02c::Send {Blind}{U+002c} ; ,

; QWERTY X
#if not Extend
SC02d::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+007a} ; z
} else {
  Send {Blind}{U+005a} ; Z
}
Return
+SC02d::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+005a} ; Z
} else {
  Send {Blind}{U+007a} ; z
}
Return
>!<^SC02d::Send {Blind}{U+0026} ; &
#if Extend
*SC02d::Send {Blind}{U+0033} ; 3
+SC02d::Send {Blind}{U+0033} ; 3

; QWERTY C
#if not Extend
SC02e::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0078} ; x
} else {
  Send {Blind}{U+0058} ; X
}
Return
+SC02e::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0058} ; X
} else {
  Send {Blind}{U+0078} ; x
}
Return
>!<^SC02e::Send {Blind}{U+003d} ; =
#if Extend
*SC02e::Send {Blind}{U+0032} ; 2
+SC02e::Send {Blind}{U+0032} ; 2

; QWERTY V
#if not Extend
SC02f::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+006b} ; k
} else {
  Send {Blind}{U+004b} ; K
}
Return
+SC02f::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+004b} ; K
} else {
  Send {Blind}{U+006b} ; k
}
Return
>!<^SC02f::Send {Blind}{U+002a} ; *
#if Extend
*SC02f::Send {Blind}{U+0031} ; 1
+SC02f::Send {Blind}{U+0031} ; 1

; QWERTY B
#if not Extend
SC030::Send {Blind}{U+002d} ; -
+SC030::Send {Blind}{U+005f} ; _
>!<^SC030::Send {Blind}{U+2010} ; ‐
+>!<^SC030::Send {Blind}{U+2013} ; –
#if Extend
*SC030::Send {Blind}{U+002d} ; -
+SC030::Send {Blind}{U+002d} ; -

; QWERTY N
#if not Extend
SC031::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0062} ; b
} else {
  Send {Blind}{U+0042} ; B
}
Return
+SC031::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0042} ; B
} else {
  Send {Blind}{U+0062} ; b
}
Return
#if Extend
*SC031::Send {Blind}{U+002d} ; -
+SC031::Send {Blind}{U+002d} ; -

; QWERTY M
#if not Extend
SC032::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+006d} ; m
} else {
  Send {Blind}{U+004d} ; M
}
Return
+SC032::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+004d} ; M
} else {
  Send {Blind}{U+006d} ; m
}
Return
>!<^SC032::Send {Blind}{U+007e} ; ~
#if Extend
*SC032::Send {Blind}{U+0031} ; 1
+SC032::Send {Blind}{U+0031} ; 1

; QWERTY ,
#if not Extend
SC033::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0077} ; w
} else {
  Send {Blind}{U+0057} ; W
}
Return
+SC033::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0057} ; W
} else {
  Send {Blind}{U+0077} ; w
}
Return
>!<^SC033::Send {Blind}{U+007c} ; |
#if Extend
*SC033::Send {Blind}{U+0032} ; 2
+SC033::Send {Blind}{U+0032} ; 2

; QWERTY .
#if not Extend
SC034::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0076} ; v
} else {
  Send {Blind}{U+0056} ; V
}
Return
+SC034::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0056} ; V
} else {
  Send {Blind}{U+0076} ; v
}
Return
>!<^SC034::Send {Blind}{U+0025} ; %
#if Extend
*SC034::Send {Blind}{U+0033} ; 3
+SC034::Send {Blind}{U+0033} ; 3

; QWERTY /
#if not Extend
SC035::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0066} ; f
} else {
  Send {Blind}{U+0046} ; F
}
Return
+SC035::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0046} ; F
} else {
  Send {Blind}{U+0066} ; f
}
Return
>!<^SC035::Send {Blind}{U+00a2} ; ¢
#if Extend
*SC035::Send {Blind}{U+002c} ; ,
+SC035::Send {Blind}{U+002c} ; ,

; QWERTY A
#if not Extend
SC01e::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0061} ; a
} else {
  Send {Blind}{U+0041} ; A
}
Return
+SC01e::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0041} ; A
} else {
  Send {Blind}{U+0061} ; a
}
Return
>!<^SC01e::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+005b} ; [
} else {
  Send {Blind}{U+00aa} ; ª
}
Return
+>!<^SC01e::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00aa} ; ª
} else {
  Send {Blind}{U+005b} ; [
}
Return
#if Extend
*SC01e::Send {Blind}{U+002e} ; .
+SC01e::Send {Blind}{U+002e} ; .

; QWERTY S
#if not Extend
SC01f::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0073} ; s
} else {
  Send {Blind}{U+0053} ; S
}
Return
+SC01f::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0053} ; S
} else {
  Send {Blind}{U+0073} ; s
}
Return
>!<^SC01f::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+005d} ; ]
} else {
  Send {Blind}{U+00a4} ; ¤
}
Return
+>!<^SC01f::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00a4} ; ¤
} else {
  Send {Blind}{U+005d} ; ]
}
Return
#if Extend
*SC01f::Send {Blind}{U+0036} ; 6
+SC01f::Send {Blind}{U+0036} ; 6

; QWERTY D
#if not Extend
SC020::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0065} ; e
} else {
  Send {Blind}{U+0045} ; E
}
Return
+SC020::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0045} ; E
} else {
  Send {Blind}{U+0065} ; e
}
Return
>!<^SC020::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+002f} ; /
} else {
  Send {Blind}{U+20ac} ; €
}
Return
+>!<^SC020::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+20ac} ; €
} else {
  Send {Blind}{U+002f} ; /
}
Return
#if Extend
*SC020::Send {Blind}{U+0035} ; 5
+SC020::Send {Blind}{U+0035} ; 5

; QWERTY F
#if not Extend
SC021::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0075} ; u
} else {
  Send {Blind}{U+0055} ; U
}
Return
+SC021::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0055} ; U
} else {
  Send {Blind}{U+0075} ; u
}
Return
>!<^SC021::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+005c} ; \
} else {
  Send {Blind}{U+03bc} ; μ
}
Return
+>!<^SC021::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+03bc} ; μ
} else {
  Send {Blind}{U+005c} ; \
}
Return
#if Extend
*SC021::Send {Blind}{U+0034} ; 4
+SC021::Send {Blind}{U+0034} ; 4

; QWERTY G
#if not Extend
SC022::Send {Blind}{U+002c} ; ,
+SC022::Send {Blind}{U+003c} ; <
>!<^SC022::Send {Blind}{U+00ab} ; «
#if Extend
*SC022::Send {Blind}{U+002b} ; +
+SC022::Send {Blind}{U+002b} ; +

; QWERTY H
#if not Extend
SC023::Send {Blind}{U+002e} ; .
+SC023::Send {Blind}{U+003e} ; >
>!<^SC023::Send {Blind}{U+00bb} ; »
#if Extend
*SC023::Send {Blind}{U+002b} ; +
+SC023::Send {Blind}{U+002b} ; +

; QWERTY J
#if not Extend
SC024::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+006f} ; o
} else {
  Send {Blind}{U+004f} ; O
}
Return
+SC024::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+004f} ; O
} else {
  Send {Blind}{U+006f} ; o
}
Return
>!<^SC024::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0027} ; '
} else {
  Send {Blind}{U+00ba} ; º
}
Return
+>!<^SC024::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00ba} ; º
} else {
  Send {Blind}{U+0027} ; '
}
Return
#if Extend
*SC024::Send {Blind}{U+0034} ; 4
+SC024::Send {Blind}{U+0034} ; 4

; QWERTY K
#if not Extend
SC025::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0074} ; t
} else {
  Send {Blind}{U+0054} ; T
}
Return
+SC025::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0054} ; T
} else {
  Send {Blind}{U+0074} ; t
}
Return
>!<^SC025::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0022} ; "
} else {
  Send {Blind}{U+00a9} ; ©
}
Return
+>!<^SC025::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00a9} ; ©
} else {
  Send {Blind}{U+0022} ; "
}
Return
#if Extend
*SC025::Send {Blind}{U+0035} ; 5
+SC025::Send {Blind}{U+0035} ; 5

; QWERTY L
#if not Extend
SC026::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0068} ; h
} else {
  Send {Blind}{U+0048} ; H
}
Return
+SC026::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0048} ; H
} else {
  Send {Blind}{U+0068} ; h
}
Return
>!<^SC026::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0060} ; `
} else {
  Send {Blind}{U+00ae} ; ®
}
Return
+>!<^SC026::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00ae} ; ®
} else {
  Send {Blind}{U+0060} ; `
}
Return
#if Extend
*SC026::Send {Blind}{U+0036} ; 6
+SC026::Send {Blind}{U+0036} ; 6

; QWERTY ;
#if not Extend
SC027::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+006e} ; n
} else {
  Send {Blind}{U+004e} ; N
}
Return
+SC027::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+004e} ; N
} else {
  Send {Blind}{U+006e} ; n
}
Return
>!<^SC027::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00b4} ; ´
} else {
  Send {Blind}{U+2122} ; ™
}
Return
+>!<^SC027::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+2122} ; ™
} else {
  Send {Blind}{U+00b4} ; ´
}
Return
#if Extend
*SC027::Send {Blind}{U+002e} ; .
+SC027::Send {Blind}{U+002e} ; .

; QWERTY '
#if
SC028::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0071} ; q
} else {
  Send {Blind}{U+0051} ; Q
}
Return
+SC028::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0051} ; Q
} else {
  Send {Blind}{U+0071} ; q
}
Return

; QWERTY Q
#if not Extend
SC010::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0069} ; i
} else {
  Send {Blind}{U+0049} ; I
}
Return
+SC010::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0049} ; I
} else {
  Send {Blind}{U+0069} ; i
}
Return
>!<^SC010::Send {Blind}{U+0028} ; (
#if Extend
*SC010::Send {Blind}{U+0025} ; %
+SC010::Send {Blind}{U+0025} ; %

; QWERTY W
#if not Extend
SC011::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0064} ; d
} else {
  Send {Blind}{U+0044} ; D
}
Return
+SC011::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0044} ; D
} else {
  Send {Blind}{U+0064} ; d
}
Return
>!<^SC011::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0029} ; )
} else {
  Send {Blind}{U+0024} ; $
}
Return
+>!<^SC011::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0024} ; $
} else {
  Send {Blind}{U+0029} ; )
}
Return
#if Extend
*SC011::Send {Blind}{U+0039} ; 9
+SC011::Send {Blind}{U+0039} ; 9

; QWERTY E
#if not Extend
SC012::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0079} ; y
} else {
  Send {Blind}{U+0059} ; Y
}
Return
+SC012::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0059} ; Y
} else {
  Send {Blind}{U+0079} ; y
}
Return
>!<^SC012::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+007b} ; {
} else {
  Send {Blind}{U+00a5} ; ¥
}
Return
+>!<^SC012::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00a5} ; ¥
} else {
  Send {Blind}{U+007b} ; {
}
Return
#if Extend
*SC012::Send {Blind}{U+0038} ; 8
+SC012::Send {Blind}{U+0038} ; 8

; QWERTY R
#if not Extend
SC013::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0070} ; p
} else {
  Send {Blind}{U+0050} ; P
}
Return
+SC013::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0050} ; P
} else {
  Send {Blind}{U+0070} ; p
}
Return
>!<^SC013::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+007d} ; }
} else {
  Send {Blind}{U+00a3} ; £
}
Return
+>!<^SC013::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00a3} ; £
} else {
  Send {Blind}{U+007d} ; }
}
Return
#if Extend
*SC013::Send {Blind}{U+0037} ; 7
+SC013::Send {Blind}{U+0037} ; 7

; QWERTY T
#if not Extend
SC014::Send {Blind}{U+003b} ; ;
+SC014::Send {Blind}{U+003a} ; :
>!<^SC014::Send {Blind}{U+00b0} ; °
#if Extend
*SC014::Send {Blind}{U+002f} ; /
+SC014::Send {Blind}{U+00f7} ; ÷

; QWERTY Y
#if not Extend
SC015::Send {Blind}{U+002b} ; +
+SC015::Send {Blind}{U+0040} ; @
#if Extend
*SC015::Send {Blind}{U+002f} ; /
+SC015::Send {Blind}{U+00f7} ; ÷

; QWERTY U
#if not Extend
SC016::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0067} ; g
} else {
  Send {Blind}{U+0047} ; G
}
Return
+SC016::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0047} ; G
} else {
  Send {Blind}{U+0067} ; g
}
Return
>!<^SC016::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+005e} ; ^
} else {
  Send {Blind}{U+00bd} ; ½
}
Return
+>!<^SC016::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00bd} ; ½
} else {
  Send {Blind}{U+005e} ; ^
}
Return
#if Extend
*SC016::Send {Blind}{U+0037} ; 7
+SC016::Send {Blind}{U+0037} ; 7

; QWERTY I
#if not Extend
SC017::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0063} ; c
} else {
  Send {Blind}{U+0043} ; C
}
Return
+SC017::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0043} ; C
} else {
  Send {Blind}{U+0063} ; c
}
Return
>!<^SC017::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+003f} ; ?
} else {
  Send {Blind}{U+00bf} ; ¿
}
Return
+>!<^SC017::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00bf} ; ¿
} else {
  Send {Blind}{U+003f} ; ?
}
Return
#if Extend
*SC017::Send {Blind}{U+0038} ; 8
+SC017::Send {Blind}{U+0038} ; 8

; QWERTY O
#if not Extend
SC018::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0072} ; r
} else {
  Send {Blind}{U+0052} ; R
}
Return
+SC018::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0052} ; R
} else {
  Send {Blind}{U+0072} ; r
}
Return
>!<^SC018::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0021} ; !
} else {
  Send {Blind}{U+00a1} ; ¡
}
Return
+>!<^SC018::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00a1} ; ¡
} else {
  Send {Blind}{U+0021} ; !
}
Return
#if Extend
*SC018::Send {Blind}{U+0039} ; 9
+SC018::Send {Blind}{U+0039} ; 9

; QWERTY P
#if not Extend
SC019::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+006c} ; l
} else {
  Send {Blind}{U+004c} ; L
}
Return
+SC019::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+004c} ; L
} else {
  Send {Blind}{U+006c} ; l
}
Return
#if Extend
*SC019::Send {Blind}{U+0025} ; %
+SC019::Send {Blind}{U+0025} ; %

; QWERTY [
#if
SC01a::Send {Blind}{U+0024} ; $

; QWERTY ]

; QWERTY 1

; QWERTY 2
#if
SC003::
; tilde
if (DeadKeys.item("tilde") == "") {
  DeadKeys.item("tilde") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("tilde").item("A") := "Ã"
  DeadKeys.item("tilde").item("a") := "ã"
  DeadKeys.item("tilde").item("E") := "Ẽ"
  DeadKeys.item("tilde").item("e") := "ẽ"
  DeadKeys.item("tilde").item("I") := "Ĩ"
  DeadKeys.item("tilde").item("i") := "ĩ"
  DeadKeys.item("tilde").item("N") := "Ñ"
  DeadKeys.item("tilde").item("n") := "ñ"
  DeadKeys.item("tilde").item("O") := "Õ"
  DeadKeys.item("tilde").item("o") := "õ"
  DeadKeys.item("tilde").item("U") := "Ũ"
  DeadKeys.item("tilde").item("u") := "ũ"
  DeadKeys.item("tilde").item("V") := "Ṽ"
  DeadKeys.item("tilde").item("v") := "ṽ"
  DeadKeys.item("tilde").item("Y") := "Ỹ"
  DeadKeys.item("tilde").item("y") := "ỹ"
}
DeadKey("~", DeadKeys.item("tilde"), "tilde")
Return
+SC003::
; abovedot
if (DeadKeys.item("abovedot") == "") {
  DeadKeys.item("abovedot") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("abovedot").item("A") := "Ȧ"
  DeadKeys.item("abovedot").item("a") := "ȧ"
  DeadKeys.item("abovedot").item("B") := "Ḃ"
  DeadKeys.item("abovedot").item("b") := "ḃ"
  DeadKeys.item("abovedot").item("C") := "Ċ"
  DeadKeys.item("abovedot").item("c") := "ċ"
  DeadKeys.item("abovedot").item("D") := "Ḋ"
  DeadKeys.item("abovedot").item("d") := "ḋ"
  DeadKeys.item("abovedot").item("E") := "Ė"
  DeadKeys.item("abovedot").item("e") := "ė"
  DeadKeys.item("abovedot").item("F") := "Ḟ"
  DeadKeys.item("abovedot").item("f") := "ḟ"
  DeadKeys.item("abovedot").item("G") := "Ġ"
  DeadKeys.item("abovedot").item("g") := "ġ"
  DeadKeys.item("abovedot").item("H") := "Ḣ"
  DeadKeys.item("abovedot").item("h") := "ḣ"
  DeadKeys.item("abovedot").item("I") := "İ"
  DeadKeys.item("abovedot").item("i") := "ı"
  DeadKeys.item("abovedot").item("M") := "Ṁ"
  DeadKeys.item("abovedot").item("m") := "ṁ"
  DeadKeys.item("abovedot").item("N") := "Ṅ"
  DeadKeys.item("abovedot").item("n") := "ṅ"
  DeadKeys.item("abovedot").item("O") := "Ȯ"
  DeadKeys.item("abovedot").item("o") := "ȯ"
  DeadKeys.item("abovedot").item("P") := "Ṗ"
  DeadKeys.item("abovedot").item("p") := "ṗ"
  DeadKeys.item("abovedot").item("R") := "Ṙ"
  DeadKeys.item("abovedot").item("r") := "ṙ"
  DeadKeys.item("abovedot").item("S") := "Ṡ"
  DeadKeys.item("abovedot").item("s") := "ṡ"
  DeadKeys.item("abovedot").item("T") := "Ṫ"
  DeadKeys.item("abovedot").item("t") := "ṫ"
  DeadKeys.item("abovedot").item("W") := "Ẇ"
  DeadKeys.item("abovedot").item("w") := "ẇ"
  DeadKeys.item("abovedot").item("X") := "Ẋ"
  DeadKeys.item("abovedot").item("x") := "ẋ"
  DeadKeys.item("abovedot").item("Y") := "Ẏ"
  DeadKeys.item("abovedot").item("y") := "ẏ"
  DeadKeys.item("abovedot").item("Z") := "Ż"
  DeadKeys.item("abovedot").item("z") := "ż"
}
DeadKey("˙", DeadKeys.item("abovedot"), "abovedot")
Return
>!<^SC003::Send {Blind}{U+00df} ; ß

; QWERTY 3
#if not Extend
SC004::
; cedilla
if (DeadKeys.item("cedilla") == "") {
  DeadKeys.item("cedilla") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("cedilla").item("C") := "Ç"
  DeadKeys.item("cedilla").item("c") := "ç"
  DeadKeys.item("cedilla").item("D") := "Ḑ"
  DeadKeys.item("cedilla").item("d") := "ḑ"
  DeadKeys.item("cedilla").item("E") := "Ȩ"
  DeadKeys.item("cedilla").item("e") := "ȩ"
  DeadKeys.item("cedilla").item("G") := "Ģ"
  DeadKeys.item("cedilla").item("g") := "ģ"
  DeadKeys.item("cedilla").item("H") := "Ḩ"
  DeadKeys.item("cedilla").item("h") := "ḩ"
  DeadKeys.item("cedilla").item("K") := "Ķ"
  DeadKeys.item("cedilla").item("k") := "ķ"
  DeadKeys.item("cedilla").item("L") := "Ļ"
  DeadKeys.item("cedilla").item("l") := "ļ"
  DeadKeys.item("cedilla").item("N") := "Ņ"
  DeadKeys.item("cedilla").item("n") := "ņ"
  DeadKeys.item("cedilla").item("R") := "Ŗ"
  DeadKeys.item("cedilla").item("r") := "ŗ"
  DeadKeys.item("cedilla").item("S") := "Ş"
  DeadKeys.item("cedilla").item("s") := "ş"
  DeadKeys.item("cedilla").item("T") := "Ţ"
  DeadKeys.item("cedilla").item("t") := "ţ"
}
DeadKey("¸", DeadKeys.item("cedilla"), "cedilla")
Return
+SC004::
; belowdot
if (DeadKeys.item("belowdot") == "") {
  DeadKeys.item("belowdot") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("belowdot").item("A") := "Ạ"
  DeadKeys.item("belowdot").item("a") := "ạ"
  DeadKeys.item("belowdot").item("B") := "Ḅ"
  DeadKeys.item("belowdot").item("b") := "ḅ"
  DeadKeys.item("belowdot").item("D") := "Ḍ"
  DeadKeys.item("belowdot").item("d") := "ḍ"
  DeadKeys.item("belowdot").item("E") := "Ẹ"
  DeadKeys.item("belowdot").item("e") := "ẹ"
  DeadKeys.item("belowdot").item("H") := "Ḥ"
  DeadKeys.item("belowdot").item("h") := "ḥ"
  DeadKeys.item("belowdot").item("I") := "Ị"
  DeadKeys.item("belowdot").item("i") := "ị"
  DeadKeys.item("belowdot").item("K") := "Ḳ"
  DeadKeys.item("belowdot").item("k") := "ḳ"
  DeadKeys.item("belowdot").item("L") := "Ḷ"
  DeadKeys.item("belowdot").item("l") := "ḷ"
  DeadKeys.item("belowdot").item("M") := "Ṃ"
  DeadKeys.item("belowdot").item("m") := "ṃ"
  DeadKeys.item("belowdot").item("N") := "Ṇ"
  DeadKeys.item("belowdot").item("n") := "ṇ"
  DeadKeys.item("belowdot").item("O") := "Ọ"
  DeadKeys.item("belowdot").item("o") := "ọ"
  DeadKeys.item("belowdot").item("R") := "Ṛ"
  DeadKeys.item("belowdot").item("r") := "ṛ"
  DeadKeys.item("belowdot").item("S") := "Ṣ"
  DeadKeys.item("belowdot").item("s") := "ṣ"
  DeadKeys.item("belowdot").item("T") := "Ṭ"
  DeadKeys.item("belowdot").item("t") := "ṭ"
  DeadKeys.item("belowdot").item("U") := "Ụ"
  DeadKeys.item("belowdot").item("u") := "ụ"
  DeadKeys.item("belowdot").item("V") := "Ṿ"
  DeadKeys.item("belowdot").item("v") := "ṿ"
  DeadKeys.item("belowdot").item("W") := "Ẉ"
  DeadKeys.item("belowdot").item("w") := "ẉ"
  DeadKeys.item("belowdot").item("Y") := "Ỵ"
  DeadKeys.item("belowdot").item("y") := "ỵ"
  DeadKeys.item("belowdot").item("Z") := "Ẓ"
  DeadKeys.item("belowdot").item("z") := "ẓ"
}
DeadKey("ࠃ", DeadKeys.item("belowdot"), "belowdot")
Return
>!<^SC004::Send {Blind}{U+00e6} ; æ
+>!<^SC004::Send {Blind}{U+00c6} ; Æ
#if Extend
*SC004::Send {Blind}{U+0028} ; (
+SC004::Send {Blind}{U+0028} ; (

; QWERTY 4
#if not Extend
SC005::
; stroke
if (DeadKeys.item("stroke") == "") {
  DeadKeys.item("stroke") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("stroke").item("O") := "Ø"
  DeadKeys.item("stroke").item("o") := "ø"
  DeadKeys.item("stroke").item("D") := "Đ"
  DeadKeys.item("stroke").item("d") := "đ"
  DeadKeys.item("stroke").item("H") := "Ħ"
  DeadKeys.item("stroke").item("h") := "ħ"
  DeadKeys.item("stroke").item("L") := "Ł"
  DeadKeys.item("stroke").item("l") := "ł"
  DeadKeys.item("stroke").item("T") := "Ŧ"
  DeadKeys.item("stroke").item("t") := "ŧ"
  DeadKeys.item("stroke").item("b") := "ƀ"
  DeadKeys.item("stroke").item("I") := "Ɨ"
  DeadKeys.item("stroke").item("z") := "ƶ"
  DeadKeys.item("stroke").item("G") := "Ǥ"
  DeadKeys.item("stroke").item("g") := "ǥ"
  DeadKeys.item("stroke").item("Ó") := "Ǿ"
  DeadKeys.item("stroke").item("ó") := "ǿ"
  DeadKeys.item("stroke").item("i") := "ɨ"
  DeadKeys.item("stroke").item("=") := "≠"
  DeadKeys.item("stroke").item("A") := "Ⱥ"
  DeadKeys.item("stroke").item("a") := "ⱥ"
  DeadKeys.item("stroke").item("B") := "Ƀ"
  DeadKeys.item("stroke").item("C") := "Ȼ"
  DeadKeys.item("stroke").item("c") := "ȼ"
  DeadKeys.item("stroke").item("E") := "Ɇ"
  DeadKeys.item("stroke").item("e") := "ɇ"
  DeadKeys.item("stroke").item(">") := "≯"
  DeadKeys.item("stroke").item("≥") := "≱"
  DeadKeys.item("stroke").item("J") := "Ɉ"
  DeadKeys.item("stroke").item("j") := "ɉ"
  DeadKeys.item("stroke").item("ɩ") := "ᵼ"
  DeadKeys.item("stroke").item("ȷ") := "ɟ"
  DeadKeys.item("stroke").item("<") := "≮"
  DeadKeys.item("stroke").item("≤") := "≰"
  DeadKeys.item("stroke").item("P") := "Ᵽ"
  DeadKeys.item("stroke").item("p") := "ᵽ"
  DeadKeys.item("stroke").item("R") := "Ɍ"
  DeadKeys.item("stroke").item("r") := "ɍ"
  DeadKeys.item("stroke").item("U") := "Ʉ"
  DeadKeys.item("stroke").item("u") := "ʉ"
  DeadKeys.item("stroke").item("Y") := "Ɏ"
  DeadKeys.item("stroke").item("y") := "ɏ"
}
DeadKey("/", DeadKeys.item("stroke"), "stroke")
Return
+SC005::
; abovering
if (DeadKeys.item("abovering") == "") {
  DeadKeys.item("abovering") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("abovering").item("A") := "Å"
  DeadKeys.item("abovering").item("a") := "å"
  DeadKeys.item("abovering").item("U") := "Ů"
  DeadKeys.item("abovering").item("u") := "ů"
  DeadKeys.item("abovering").item("w") := "ẘ"
  DeadKeys.item("abovering").item("y") := "ẙ"
}
DeadKey("˚", DeadKeys.item("abovering"), "abovering")
Return
>!<^SC005::Send {Blind}{U+0153} ; œ
+>!<^SC005::Send {Blind}{U+0152} ; Œ
#if Extend
*SC005::Send {Blind}{U+0029} ; )
+SC005::Send {Blind}{U+0029} ; )

; QWERTY 5
#if not Extend
SC006::
; caron
if (DeadKeys.item("caron") == "") {
  DeadKeys.item("caron") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("caron").item("A") := "Ǎ"
  DeadKeys.item("caron").item("a") := "ǎ"
  DeadKeys.item("caron").item("C") := "Č"
  DeadKeys.item("caron").item("c") := "č"
  DeadKeys.item("caron").item("D") := "Ď"
  DeadKeys.item("caron").item("d") := "ď"
  DeadKeys.item("caron").item("E") := "Ě"
  DeadKeys.item("caron").item("e") := "ě"
  DeadKeys.item("caron").item("G") := "Ǧ"
  DeadKeys.item("caron").item("g") := "ǧ"
  DeadKeys.item("caron").item("H") := "Ȟ"
  DeadKeys.item("caron").item("h") := "ȟ"
  DeadKeys.item("caron").item("I") := "Ǐ"
  DeadKeys.item("caron").item("i") := "ǐ"
  DeadKeys.item("caron").item("j") := "ǰ"
  DeadKeys.item("caron").item("K") := "Ǩ"
  DeadKeys.item("caron").item("k") := "ǩ"
  DeadKeys.item("caron").item("L") := "Ľ"
  DeadKeys.item("caron").item("l") := "ľ"
  DeadKeys.item("caron").item("N") := "Ň"
  DeadKeys.item("caron").item("n") := "ň"
  DeadKeys.item("caron").item("O") := "Ǒ"
  DeadKeys.item("caron").item("o") := "ǒ"
  DeadKeys.item("caron").item("R") := "Ř"
  DeadKeys.item("caron").item("r") := "ř"
  DeadKeys.item("caron").item("S") := "Š"
  DeadKeys.item("caron").item("s") := "š"
  DeadKeys.item("caron").item("T") := "Ť"
  DeadKeys.item("caron").item("t") := "ť"
  DeadKeys.item("caron").item("U") := "Ǔ"
  DeadKeys.item("caron").item("u") := "ǔ"
  DeadKeys.item("caron").item("Z") := "Ž"
  DeadKeys.item("caron").item("z") := "ž"
  DeadKeys.item("caron").item("Ʒ") := "Ǯ"
  DeadKeys.item("caron").item("ʒ") := "ǯ"
}
DeadKey("ˇ", DeadKeys.item("caron"), "caron")
Return
+SC006::
; breve
if (DeadKeys.item("breve") == "") {
  DeadKeys.item("breve") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("breve").item("A") := "Ă"
  DeadKeys.item("breve").item("a") := "ă"
  DeadKeys.item("breve").item("E") := "Ĕ"
  DeadKeys.item("breve").item("e") := "ĕ"
  DeadKeys.item("breve").item("G") := "Ğ"
  DeadKeys.item("breve").item("g") := "ğ"
  DeadKeys.item("breve").item("I") := "Ĭ"
  DeadKeys.item("breve").item("i") := "ĭ"
  DeadKeys.item("breve").item("O") := "Ŏ"
  DeadKeys.item("breve").item("o") := "ŏ"
  DeadKeys.item("breve").item("U") := "Ŭ"
  DeadKeys.item("breve").item("u") := "ŭ"
}
DeadKey("˘", DeadKeys.item("breve"), "breve")
Return
>!<^SC006::Send {Blind}{U+00fe} ; þ
+>!<^SC006::Send {Blind}{U+00de} ; Þ
#if Extend
*SC006::Send {Blind}{U+002a} ; *
+SC006::Send {Blind}{U+00d7} ; ×

; QWERTY 6
#if not Extend
SC007::
; horn
if (DeadKeys.item("horn") == "") {
  DeadKeys.item("horn") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("horn").item("O") := "Ơ"
  DeadKeys.item("horn").item("o") := "ơ"
  DeadKeys.item("horn").item("U") := "Ư"
  DeadKeys.item("horn").item("u") := "ư"
}
DeadKey("̛", DeadKeys.item("horn"), "horn")
Return
#if Extend
*SC007::Send {Blind}{U+003d} ; =
+SC007::Send {Blind}{U+003d} ; =

; QWERTY 7
#if Extend
*SC008::Send {Blind}{U+002a} ; *
+SC008::Send {Blind}{U+00d7} ; ×

; QWERTY 8
#if not Extend
SC009::
; diaeresis
if (DeadKeys.item("diaeresis") == "") {
  DeadKeys.item("diaeresis") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("diaeresis").item(" ") := """"
  DeadKeys.item("diaeresis").item("A") := "Ä"
  DeadKeys.item("diaeresis").item("a") := "ä"
  DeadKeys.item("diaeresis").item("E") := "Ë"
  DeadKeys.item("diaeresis").item("e") := "ë"
  DeadKeys.item("diaeresis").item("H") := "Ḧ"
  DeadKeys.item("diaeresis").item("h") := "ḧ"
  DeadKeys.item("diaeresis").item("I") := "Ï"
  DeadKeys.item("diaeresis").item("i") := "ï"
  DeadKeys.item("diaeresis").item("O") := "Ö"
  DeadKeys.item("diaeresis").item("o") := "ö"
  DeadKeys.item("diaeresis").item("t") := "ẗ"
  DeadKeys.item("diaeresis").item("U") := "Ü"
  DeadKeys.item("diaeresis").item("u") := "ü"
  DeadKeys.item("diaeresis").item("W") := "Ẅ"
  DeadKeys.item("diaeresis").item("w") := "ẅ"
  DeadKeys.item("diaeresis").item("X") := "Ẍ"
  DeadKeys.item("diaeresis").item("x") := "ẍ"
  DeadKeys.item("diaeresis").item("Y") := "Ÿ"
  DeadKeys.item("diaeresis").item("y") := "ÿ"
}
DeadKey("¨", DeadKeys.item("diaeresis"), "diaeresis")
Return
+SC009::
; hook
if (DeadKeys.item("hook") == "") {
  DeadKeys.item("hook") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("hook").item("A") := "Ả"
  DeadKeys.item("hook").item("a") := "ả"
  DeadKeys.item("hook").item("Ă") := "Ẳ"
  DeadKeys.item("hook").item("ă") := "ẳ"
  DeadKeys.item("hook").item("Â") := "Ẩ"
  DeadKeys.item("hook").item("â") := "ẩ"
  DeadKeys.item("hook").item("E") := "Ẻ"
  DeadKeys.item("hook").item("e") := "ẻ"
  DeadKeys.item("hook").item("Ê") := "Ể"
  DeadKeys.item("hook").item("ê") := "ể"
  DeadKeys.item("hook").item("I") := "Ỉ"
  DeadKeys.item("hook").item("i") := "ỉ"
  DeadKeys.item("hook").item("O") := "Ỏ"
  DeadKeys.item("hook").item("o") := "ỏ"
  DeadKeys.item("hook").item("Ô") := "Ổ"
  DeadKeys.item("hook").item("ô") := "ổ"
  DeadKeys.item("hook").item("Ơ") := "Ở"
  DeadKeys.item("hook").item("ơ") := "ở"
  DeadKeys.item("hook").item("U") := "Ủ"
  DeadKeys.item("hook").item("u") := "ủ"
  DeadKeys.item("hook").item("Ư") := "Ử"
  DeadKeys.item("hook").item("ư") := "ử"
  DeadKeys.item("hook").item("Y") := "Ỷ"
  DeadKeys.item("hook").item("y") := "ỷ"
}
DeadKey("̉", DeadKeys.item("hook"), "hook")
Return
>!<^SC009::Send {Blind}{U+00f0} ; ð
+>!<^SC009::Send {Blind}{U+00d0} ; Ð
#if Extend
*SC009::Send {Blind}{U+0028} ; (
+SC009::Send {Blind}{U+0028} ; (

; QWERTY 9
#if not Extend
SC00a::
; acute
if (DeadKeys.item("acute") == "") {
  DeadKeys.item("acute") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("acute").item(" ") := "'"
  DeadKeys.item("acute").item("A") := "Á"
  DeadKeys.item("acute").item("a") := "á"
  DeadKeys.item("acute").item("Æ") := "Ǽ"
  DeadKeys.item("acute").item("æ") := "ǽ"
  DeadKeys.item("acute").item("C") := "Ć"
  DeadKeys.item("acute").item("c") := "ć"
  DeadKeys.item("acute").item("E") := "É"
  DeadKeys.item("acute").item("e") := "é"
  DeadKeys.item("acute").item("G") := "Ǵ"
  DeadKeys.item("acute").item("g") := "ǵ"
  DeadKeys.item("acute").item("I") := "Í"
  DeadKeys.item("acute").item("i") := "í"
  DeadKeys.item("acute").item("K") := "Ḱ"
  DeadKeys.item("acute").item("k") := "ḱ"
  DeadKeys.item("acute").item("L") := "Ĺ"
  DeadKeys.item("acute").item("l") := "ĺ"
  DeadKeys.item("acute").item("M") := "Ḿ"
  DeadKeys.item("acute").item("m") := "ḿ"
  DeadKeys.item("acute").item("N") := "Ń"
  DeadKeys.item("acute").item("n") := "ń"
  DeadKeys.item("acute").item("O") := "Ó"
  DeadKeys.item("acute").item("o") := "ó"
  DeadKeys.item("acute").item("Ø") := "Ǿ"
  DeadKeys.item("acute").item("ø") := "ǿ"
  DeadKeys.item("acute").item("P") := "Ṕ"
  DeadKeys.item("acute").item("p") := "ṕ"
  DeadKeys.item("acute").item("R") := "Ŕ"
  DeadKeys.item("acute").item("r") := "ŕ"
  DeadKeys.item("acute").item("S") := "Ś"
  DeadKeys.item("acute").item("s") := "ś"
  DeadKeys.item("acute").item("U") := "Ú"
  DeadKeys.item("acute").item("u") := "ú"
  DeadKeys.item("acute").item("W") := "Ẃ"
  DeadKeys.item("acute").item("w") := "ẃ"
  DeadKeys.item("acute").item("Y") := "Ý"
  DeadKeys.item("acute").item("y") := "ý"
  DeadKeys.item("acute").item("Z") := "Ź"
  DeadKeys.item("acute").item("z") := "ź"
}
DeadKey("´", DeadKeys.item("acute"), "acute")
Return
+SC00a::
; doubleacute
if (DeadKeys.item("doubleacute") == "") {
  DeadKeys.item("doubleacute") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("doubleacute").item("O") := "Ő"
  DeadKeys.item("doubleacute").item("o") := "ő"
  DeadKeys.item("doubleacute").item("U") := "Ű"
  DeadKeys.item("doubleacute").item("u") := "ű"
}
DeadKey("˝", DeadKeys.item("doubleacute"), "doubleacute")
Return
>!<^SC00a::Send {Blind}{U+014b} ; ŋ
+>!<^SC00a::Send {Blind}{U+014a} ; Ŋ
#if Extend
*SC00a::Send {Blind}{U+0029} ; )
+SC00a::Send {Blind}{U+0029} ; )

; QWERTY 0
#if
SC00b::
; grave
if (DeadKeys.item("grave") == "") {
  DeadKeys.item("grave") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("grave").item(" ") := "``"
  DeadKeys.item("grave").item("A") := "À"
  DeadKeys.item("grave").item("a") := "à"
  DeadKeys.item("grave").item("E") := "È"
  DeadKeys.item("grave").item("e") := "è"
  DeadKeys.item("grave").item("I") := "Ì"
  DeadKeys.item("grave").item("i") := "ì"
  DeadKeys.item("grave").item("N") := "Ǹ"
  DeadKeys.item("grave").item("n") := "ǹ"
  DeadKeys.item("grave").item("O") := "Ò"
  DeadKeys.item("grave").item("o") := "ò"
  DeadKeys.item("grave").item("U") := "Ù"
  DeadKeys.item("grave").item("u") := "ù"
  DeadKeys.item("grave").item("W") := "Ẁ"
  DeadKeys.item("grave").item("w") := "ẁ"
  DeadKeys.item("grave").item("Y") := "Ỳ"
  DeadKeys.item("grave").item("y") := "ỳ"
}
DeadKey("``", DeadKeys.item("grave"), "grave")
Return
+SC00b::
; ogonek
if (DeadKeys.item("ogonek") == "") {
  DeadKeys.item("ogonek") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("ogonek").item("A") := "Ą"
  DeadKeys.item("ogonek").item("a") := "ą"
  DeadKeys.item("ogonek").item("E") := "Ę"
  DeadKeys.item("ogonek").item("e") := "ę"
  DeadKeys.item("ogonek").item("I") := "Į"
  DeadKeys.item("ogonek").item("i") := "į"
  DeadKeys.item("ogonek").item("O") := "Ǫ"
  DeadKeys.item("ogonek").item("o") := "ǫ"
  DeadKeys.item("ogonek").item("U") := "Ų"
  DeadKeys.item("ogonek").item("u") := "ų"
}
DeadKey("˛", DeadKeys.item("ogonek"), "ogonek")
Return
>!<^SC00b::Send {Blind}{U+0133} ; ĳ
+>!<^SC00b::Send {Blind}{U+0132} ; Ĳ

; QWERTY -
#if
SC00c::
; circumflex
if (DeadKeys.item("circumflex") == "") {
  DeadKeys.item("circumflex") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("circumflex").item(" ") := "^"
  DeadKeys.item("circumflex").item("A") := "Â"
  DeadKeys.item("circumflex").item("a") := "â"
  DeadKeys.item("circumflex").item("C") := "Ĉ"
  DeadKeys.item("circumflex").item("c") := "ĉ"
  DeadKeys.item("circumflex").item("E") := "Ê"
  DeadKeys.item("circumflex").item("e") := "ê"
  DeadKeys.item("circumflex").item("G") := "Ĝ"
  DeadKeys.item("circumflex").item("g") := "ĝ"
  DeadKeys.item("circumflex").item("H") := "Ĥ"
  DeadKeys.item("circumflex").item("h") := "ĥ"
  DeadKeys.item("circumflex").item("I") := "Î"
  DeadKeys.item("circumflex").item("i") := "î"
  DeadKeys.item("circumflex").item("J") := "Ĵ"
  DeadKeys.item("circumflex").item("j") := "ĵ"
  DeadKeys.item("circumflex").item("O") := "Ô"
  DeadKeys.item("circumflex").item("o") := "ô"
  DeadKeys.item("circumflex").item("S") := "Ŝ"
  DeadKeys.item("circumflex").item("s") := "ŝ"
  DeadKeys.item("circumflex").item("U") := "Û"
  DeadKeys.item("circumflex").item("u") := "û"
  DeadKeys.item("circumflex").item("W") := "Ŵ"
  DeadKeys.item("circumflex").item("w") := "ŵ"
  DeadKeys.item("circumflex").item("Y") := "Ŷ"
  DeadKeys.item("circumflex").item("y") := "ŷ"
  DeadKeys.item("circumflex").item("Z") := "Ẑ"
  DeadKeys.item("circumflex").item("z") := "ẑ"
}
DeadKey("^", DeadKeys.item("circumflex"), "circumflex")
Return
+SC00c::
; macron
if (DeadKeys.item("macron") == "") {
  DeadKeys.item("macron") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("macron").item("A") := "Ā"
  DeadKeys.item("macron").item("a") := "ā"
  DeadKeys.item("macron").item("E") := "Ē"
  DeadKeys.item("macron").item("e") := "ē"
  DeadKeys.item("macron").item("G") := "Ḡ"
  DeadKeys.item("macron").item("g") := "ḡ"
  DeadKeys.item("macron").item("I") := "Ī"
  DeadKeys.item("macron").item("i") := "ī"
  DeadKeys.item("macron").item("O") := "Ō"
  DeadKeys.item("macron").item("o") := "ō"
  DeadKeys.item("macron").item("U") := "Ū"
  DeadKeys.item("macron").item("u") := "ū"
  DeadKeys.item("macron").item("Y") := "Ȳ"
  DeadKeys.item("macron").item("y") := "ȳ"
  DeadKeys.item("macron").item("Æ") := "Ǣ"
  DeadKeys.item("macron").item("æ") := "ǣ"
}
DeadKey("¯", DeadKeys.item("macron"), "macron")
Return

; QWERTY +

; QWERTY \

; QWERTY Backspace
#if not Extend
SC00e::Send {BackSpace}
+SC00e::Send {BackSpace}
>!<^SC00e::Send {BackSpace}
+>!<^SC00e::Send {BackSpace}
#if Extend
*SC00e::Send {Blind}{BackSpace}
+SC00e::Send {BackSpace}

; QWERTY Space
#if not Extend
SC039::Send {Blind}{U+0020} ;  
+SC039::Send {Blind}{U+0020} ;  
>!<^SC039::Send {Blind}{U+0020} ;  
+>!<^SC039::Send {Blind}{U+0020} ;  
#if Extend
*SC039::Send {Blind}{U+0030} ; 0
+SC039::Send {Blind}{U+0030} ; 0

; QWERTY CapsLock
#if
SC03a::
Extend := true
if (ModsSC03a == "")
  ModsSC03a := Object()
ModsSC03a.Insert("Extend")
Return

; QWERTY Shift_L
#if
SC02a::
Send {Shift Down}
if (ModsSC02a == "")
  ModsSC02a := Object()
ModsSC02a.Insert("Shift")
Return
+SC02a::
if (LockedSC02a)
  Send {Shift Up}
else
  Send {Shift Down}
LockedSC02a := not LockedSC02a
Return

; QWERTY Shift_R
#if
SC036::
Send {RShift Down}
if (ModsSC036 == "")
  ModsSC036 := Object()
ModsSC036.Insert("RShift")
Return
+SC036::
if (LockedSC036)
  Send {Shift Up}
else
  Send {Shift Down}
LockedSC036 := not LockedSC036
Return
